=== keymint/keymint_package/keymint_package/template/keyage/keyage.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:element name="keyage" type="Keyage" />
    <xs:complexType name="Keyage">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="name" type="NameType" minOccurs="1"/>
            <xs:element name="version" type="VersionType" minOccurs="0"/>
            <xs:element name="description" type="DescriptionType" minOccurs="0"/>
            <xs:element name="permissions" type="Permissions" minOccurs="0"/>
            <xs:element name="governances" type="Governances" minOccurs="0"/>
            <xs:element name="identities" type="Identities" minOccurs="0"/>
            <xs:element name="export" type="ExportType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="format" fixed="1" use="required"/>
    </xs:complexType>

    <xs:simpleType name="NameType">
        <xs:annotation>
            <xs:documentation>
                The package name should be unique within the workspace.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:pattern value="([^/ ]+/*)+(?&lt;!/)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="VersionType">
        <xs:annotation>
            <xs:documentation>
                The version number must have the form "X.Y.Z" where X, Y, and Z
                are non-negative integers, and must not contain leading zeroes.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:pattern value="(0|[1-9][0-9]*)(.(0|[1-9][0-9]*)){2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="DescriptionType" mixed="true">
        <xs:annotation>
            <xs:documentation>
                The description allows any content but should be limit to XHTML.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExportType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="build_type" type="BuildType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="BuildType">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="Permissions">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="permission" type="Permission" />
        </xs:sequence>
        <xs:attribute name="format" fixed="keymint_ros2_dds" use="required"/>
    </xs:complexType>

    <xs:complexType name="Permission">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="path" type="PathType" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Governances">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="governance" type="Governance" />
        </xs:sequence>
        <xs:attribute name="format" fixed="keymint_ros2_dds" use="required"/>
    </xs:complexType>

    <xs:complexType name="Governance">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="path" type="PathType" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Identities">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="identity" type="Identity" />
        </xs:sequence>
        <xs:attribute name="format" fixed="keymint_ros2_dds" use="required"/>
    </xs:complexType>

    <xs:complexType name="Identity">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="path" type="PathType" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PathType">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

</xs:schema>

=== keymint/keymint_package/test/resources/keyage.xml
<?xml version="1.0" encoding="UTF-8"?>
<keyage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://example.com/ns/collection/keyage.xsd"
    format="1">
    <name>foo/bar</name>
    <permissions format="keymint_ros2_dds">
        <permission>
          <path>permissions1.xml</path>
        </permission>
        <permission>
          <path>permissions2.xml</path>
        </permission>
    </permissions>
    <export>
        <build_type>keymint_ros2_dds</build_type>
    </export>
</keyage>
